# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efba07e320f451d934bcd57372a58712dd1b0b5987994248172947153da17a80a420ecaa2c16dde6046587cda3e0994fd0a2ab3a45710cd319a582c7d7955aea

test:
  secret_key_base: 214300a7961ea28b1084b537015fbc2b2414710daaf7e0bc54df20a875d9c936f55403d05e20ccefffd61d3c463337a78482e5368ad4a730398dfdf0a83f3500

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
