# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bf7c270da27439cd4dd9221401820cf9aa68a5096f10ed94f5fe9e998ca283b41790417543850e6c676305fe3e6b1474aa902540b3b4d9e0bc76d9714c11ede

test:
  secret_key_base: 1486e406814801412629cc07e355870edc6012004dd287538bf71dc3e70c2d7018afeb6a88cab4c6dd839a24063e0e8f27ca3c90366685d871820cf04749364f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
